#CUDA_VISIBLE_DEVICES=0,1,2,3
deepspeed --master_port 1234 --num_gpus=8 finetune_pp_peft_trainer_lora_30B_deepspeed.py \
    --model_path ./LLAMA_Model/llama-30b-hf \
    --Train_dataset_path ./Data_sample/PMCandMedMCQA_itemed_Tokenized\
    --bf16 True \
    --output_dir ./Fine_Tuning_Results/PMCandMedMCQA_30B_lora \
    --num_train_epochs 3 \
    --per_device_train_batch_size 3 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --deepspeed ./configs/ds_config_zero3.json\
    --logging_steps 1 \
    --tf32 True 